// client/vueClient/src/components/AddJob.vue
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          required
          v-model="job.title"
          name="title"
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input
          class="form-control"
          id="description"
          required
          v-model="job.description"
          name="description"
        />
      </div>

      <button @click="saveJob" class="btn btn-success">Submit</button>
    </div>

    <div v-else>
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" @click="newJob">Add</button>
    </div>
  </div>
</template>

<script>
import JobDataService from "../services/JobDataService";

export default {
  name: "add-job",
  data() {
    return {
      job: {
        id: null,
        title: "",
        description: "",
        published: false,
      },
      submitted: false,
    };
  },
  methods: {
    saveJob() {
      var data = {
        title: this.job.title,
        description: this.job.description,
      };

      JobDataService.create(data)
        .then((response) => {
          this.job.id = response.data.id;
          console.log(response.data);
          this.submitted = true;
        })
        .catch((e) => {
          console.log(e);
        });
    },

    newJob() {
      this.submitted = false;
      this.job = {};
    },
  },
};
</script>

<style>
.submit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// client/angularClient/src/app/components/add-job/add-job.component.ts
import { Component, OnInit } from '@angular/core';
import { JobService } from '../../_services/job.service';

@Component({
  selector: 'app-add-job',
  templateUrl: './add-job.component.html',
  styleUrls: ['./add-job.component.css'],
})
export class AddJobComponent implements OnInit {
  job = {
    title: '',
    description: '',
    published: false,
  };
  submitted = false;

  constructor(private jobService: JobService) {}

  ngOnInit(): void {}

  saveJob(): void {
    const data = {
      title: this.job.title,
      description: this.job.description,
    };

    this.jobService.create(data).subscribe(
      (response) => {
        console.log(response);
        this.submitted = true;
      },
      (error) => {
        console.log(error);
      }
    );
  }

  newJob(): void {
    this.submitted = false;
    this.job = {
      title: '',
      description: '',
      published: false,
    };
  }
}

<div style="width: 400px; margin: auto;">
  <div class="submit-form">
    <div *ngIf="!submitted">
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          required
          [(ngModel)]="job.title"
          name="title"
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input
          class="form-control"
          id="description"
          required
          [(ngModel)]="job.description"
          name="description"
        />
      </div>

      <button (click)="saveJob()" class="btn btn-success">Submit</button>
    </div>

    <div *ngIf="submitted">
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" (click)="newJob()">Add</button>
    </div>
  </div>
</div>
